v2/backend/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from deicafe_app import views
from django.conf import settings

urlpatterns = [
  # admin
  path('admin/', admin.site.urls),

  # accounts
  path('accounts/', include(([
      path('login/', views.AccountsViewSet.Login.as_view(), name="login"),
      path('signup/', views.AccountsViewSet.SignUp.as_view(), name="signup"),
      path('logout/', views.AccountsViewSet.Logout.as_view(), name="logout")
  ], 'accounts'), namespace='accounts')),

  # user
  path('', include(([
    path('home/', views.UserViewSet.Home.as_view(), name="home"),

    path('reservation/', include([
      path('main/', views.UserViewSet.Reservation.Main.as_view(), name="reservation_main"),
      path('confirm/', views.UserViewSet.Reservation.Confirm.as_view(), name="reservation_confirm"),
      path('done/', views.UserViewSet.Reservation.Done.as_view(), name="reservation_done"),
      path('calendar/', views.UserViewSet.Reservation.Calendar.as_view(), name="reservation_calendar"),
      path('history/', views.UserViewSet.Reservation.History.as_view(), name="reservation_history"),
      path('cancel/<int:reservation_id>/', views.UserViewSet.Reservation.Cancel.as_view(), name="reservation_cancel"),
      path('cancel/<int:reservation_id>/delete/', views.UserViewSet.Reservation.Cancel.DeleteReservation.as_view(), name="reservation_delete"),
      path('cancel/<int:reservation_id>/done/', views.UserViewSet.Reservation.CancelDone.as_view(), name="reservation_cancel_done"),
      path('pre-order/', views.UserViewSet.Reservation.PreOrder.as_view(), name="reservation_pre_order"),
      path('delete_cart_item/<int:item_id>/', views.UserViewSet.Reservation.Main.DeleteCartItem.as_view(), name="delete_cart_item"),
      path('delete_reservation_draft/<int:reservation_draft_id>/', views.UserViewSet.Reservation.Main.DeleteReservationDraft.as_view(), name="delete_reservation_draft"),
    ])),

  ], 'user'), namespace='user')),

  # staff
  path('staff/', include(([
    path('home/', views.StaffViewSet.Home.as_view(), name="home"),
  ], 'staff'), namespace='staff')),
  
  # api
  path('api/signup/', views.signup_api, name='signup_api'),
  path('api/login/', views.login_api, name='login_api'),
  path('api/logout/', views.logout_api, name='logout_api'),
  path('api/user/', views.get_user_info, name='get_user_info'),
  path('api/get-csrf-token/', views.get_csrf_token, name='get_csrf_token'),

]

# save時に画面を自動リロード
if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

v2/backend/myproject/deicafe_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser


class SignUpForm(UserCreationForm):
  username = forms.CharField(
    required=True,
    widget=forms.TextInput(attrs={
      'autofocus': True,
      'placeholder': 'ユーザー名',
    }),
  )
  
  email = forms.EmailField(
    required=True,
    widget=forms.EmailInput(attrs={
      'placeholder': 'メールアドレス',
    }),
  )
  
  password = forms.CharField(
    required=True,
    widget=forms.PasswordInput(attrs={
      'placeholder': 'パスワード',
    }),
  )

  password_confirm = forms.CharField(
    required=True,
    widget=forms.PasswordInput(attrs={
      'placeholder': 'パスワード確認',
    }),
  )

  role = forms.CharField(
    initial='user',
    widget=forms.HiddenInput(),  # ユーザーには非表示
  )

  class Meta:
    model = CustomUser
    fields = ['username', 'email', 'password', 'password_confirm', 'role']


class LoginForm(AuthenticationForm):
  username = forms.EmailField(
    widget=forms.TextInput(attrs={
      'placeholder': 'メールアドレス',
      'autofocus': True,
    }),
  )

  password = forms.CharField(
    widget=forms.PasswordInput(attrs={
      'placeholder': 'パスワード'
    }),
  )

v2/backend/myproject/deicafe_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login, logout, authenticate
from .forms import SignUpForm, LoginForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from .models import \
  Reservation as ReservationModel, \
  Product as ProductModel, \
  OrderItem as OrderItemModel, \
  ReservationDraft as ReservationDraftModel, \
  CartItem as CartItemModel, \
  CustomUser as CustomUserModel
from datetime import datetime

from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.http import JsonResponse
from django.middleware.csrf import get_token
from .serializers import SignupSerializer

@api_view(['GET'])
def get_csrf_token(request):
  return JsonResponse({'csrfToken': get_token(request)})

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_user_info(request):
  user = request.user
  return Response({
    'username': user.username,
    'email': user.email,
    'role': user.role
  }, status=status.HTTP_200_OK)

@api_view(['POST'])
@csrf_exempt
def signup_api(request):
  if request.method == 'POST':
    serializer = SignupSerializer(data=request.data)
    if serializer.is_valid():
      password = request.data.get('password')
      password_confirm = request.data.get('password_confirm')
      
      if password != password_confirm:
        return Response(
          {'message': 'パスワード不一致'},
          status=status.HTTP_400_BAD_REQUEST
        )

      user = serializer.save()
      user.set_password(password)
      user.save()

      return Response(
        {'message': 'ユーザー登録完了'},
        status=status.HTTP_201_CREATED
      )
    return Response(
      serializer.errors,
      status=status.HTTP_400_BAD_REQUEST
    )

@api_view(['POST'])
@csrf_exempt
def login_api(request):
  if request.method == 'POST':
    email = request.data.get('username')
    password = request.data.get('password')
    
    user = authenticate(username=email, password=password)
    
    if user is not None:
      login(request, user)
      return Response({
        'message': 'ログイン成功',
        'username': user.username,
        'email': user.email,
        'role': user.role
      }, status=status.HTTP_200_OK)
    else:
      return Response({
        'message': '不正なログイン',
      }, status=status.HTTP_401_UNAUTHORIZED)

@api_view(['POST'])
@csrf_exempt
def logout_api(request):
  logout(request)
  return Response({'message': 'ログアウト成功'}, status=status.HTTP_200_OK)

class BaseUserView(LoginRequiredMixin, TemplateView):
  pass

class ReservationContextMixin:
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    reservations = ReservationModel.objects.filter(
      user=self.request.user
    )

    # order_items = OrderItemModel.objects.filter(
    #   reservation__in=reservations
    #   # user=self.request.user
    # )
    
    context['reservations'] = reservations
    # context['order_items'] = order_items
    context['total_price'] = sum(reservation.total_with_tax for reservation in reservations)
    return context

# LoginRequiredMixin: ログインしていない場合はログイン画面にリダイレクト
# UserPassesTestMixin: ログインしているユーザーが特定のユーザーであるかをチェック 
class UserViewSet:
  class Home(BaseUserView, UserPassesTestMixin):
    template_name = "user/home.html"
    
    # UserPassesTestMixinで使用されるメソッド
    # 特定の条件を満たすユーザのみがビューにアクセスできるようにするための認証機能
    # True -> アクセス可
    # False -> アクセス不可 403エラー
    def test_func(self):
      return self.request.user.role == 'user'
    

  class Reservation:
    class Main(BaseUserView):
      template_name = "reservation/main.html"
      
      def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation_draft = ReservationDraftModel.objects.filter(user=self.request.user).first()
        cart_items = CartItemModel.objects.filter(user=self.request.user)
        context.update({
          'reservation_draft': reservation_draft,
          'cart_items': cart_items,
        })
        return context

      class DeleteCartItem(View):
        def post(self, request, item_id):
          cart_item = CartItemModel.objects.get(id=item_id)
          cart_item.delete()
          return redirect('user:reservation_main')
      
      class DeleteReservationDraft(View):
        def post(self, request, reservation_draft_id):
          reservation_draft = ReservationDraftModel.objects.get(id=reservation_draft_id)
          reservation_draft.delete()
          return redirect('user:reservation_main')
      
    class Confirm(BaseUserView):
      template_name = "reservation/confirm.html"

      def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation_draft = ReservationDraftModel.objects.filter(user=self.request.user).first()
        cart_items = CartItemModel.objects.filter(user=self.request.user)
        context.update({
          'reservation_draft': reservation_draft,
          'cart_items': cart_items,
          'custom_user': CustomUserModel.objects.get(id=self.request.user.id)
        })
        return context

    class Done(BaseUserView):
      template_name = "reservation/done.html"
      
      # getリクエスト(~/reservation/done/に直接アクセスがあった場合)は~/reservation/confirmに遷移
      def get(self, request, *args, **kwargs):
        return redirect('user:reservation_confirm')
      
      def post(self, request, *args, **kwargs):
        # 仮予約の取得
        reservation_draft = ReservationDraftModel.objects.filter(user=self.request.user).first()
        cart_items = reservation_draft.cart_items

        # 予約情報の作成
        reservation = ReservationModel.objects.create(
          user=self.request.user,
          date=reservation_draft.date,
          time_start=reservation_draft.time_start,
          time_end=reservation_draft.time_end,
          seat_number=reservation_draft.seat_number,
          total=reservation_draft.cart_total,
          discount_amount=reservation_draft.cart_discount_amount,
          total_after_discount=reservation_draft.cart_total_after_discount,
          tax_amount=reservation_draft.cart_tax_amount,
          total_with_tax=reservation_draft.cart_total_with_tax,
          item_count=reservation_draft.item_count
        )
        
        for cart_item in cart_items:
          OrderItemModel.objects.create(
            reservation=reservation,
            product=cart_item.product,
            quantity=cart_item.quantity,
            total=cart_item.total
          )
        
        # 仮予約を削除
        reservation_draft.delete()
        cart_items.delete()
        
        context = self.get_context_data(**kwargs)
        context['reservation'] = reservation
        return self.render_to_response(context)
        
        # viewからレスポンスを返す場合は、必ず適切はHTTPレスポンスオブジェクトを返す必要があり、
        # get_context_data()は表示用のコンテキストデータの準備のみを担当し、return contextとしても親クラスのtemplate_viewのrender_to_response()が呼び出される。
        # postリクエストの場合は、return cont
        # 
        # getリクエストの場合は、return contextとしても親クラスのtemplate_viewのrender_to_response()が呼び出されるため、
        # def get_context_data()は、親クラスの処理フローに従い、コンテキストデータの準備のみを担当する。

    class Calendar(BaseUserView):
      template_name = "reservation/calendar.html"
      
      def post(self, request):
        if request.method == 'POST':
          if request.POST.get('role'):
            selected_seat = request.POST.get('role')
            context = self.get_context_data()
            context['selected_seat'] = selected_seat
            # return render(request, 'reservation/calendar.html', context)

          selected_date = datetime.strptime(request.POST.get('selected_date'), '%Y年%m月%d日')
          selected_time = request.POST.get('selected_time')
          time_end = datetime.strptime(selected_time, '%H:%M') + timedelta(hours=1)
          selected_seat = request.POST.get('selected_seat', '1')

          ReservationDraftModel.objects.create(
            user=request.user,
            date=selected_date,
            time_start=selected_time,
            time_end=time_end,
            seat_number=selected_seat
          )
          
          return redirect('user:reservation_main')

      def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.localtime()
        today = now.date()
        week_offset = int(self.request.GET.get('week_offset', 0))
        selected_seat = self.request.GET.get('seat', '1')
        reservation_number = self.request.GET.get('reservation_number', None)
        monday = today - timedelta(days=today.weekday()) + timedelta(weeks=week_offset)
        weekdates = [monday + timedelta(days=i) for i in range(7)]
        time_slots = [f'{i:02d}:00' for i in range(9, 17)]
        time_now = f'{now.time().hour:02d}:{now.time().minute:02d}'
        reservation_data = ReservationModel.objects.filter(
          date__in=weekdates,
          time_start__in=time_slots,
          seat_number=selected_seat
        )
        context['reservation_data'] = reservation_data
        DAYS_OF_WEEK = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        SEATS = ['1', '2', '3', '4', '5', '6', '7', '8']

        context['now'] = now
        context['weekdates'] = weekdates
        context['time_slots'] = time_slots
        context['DAYS_OF_WEEK'] = DAYS_OF_WEEK
        context['SEATS'] = SEATS
        context['time_now'] = time_now
        context['week_offset'] = week_offset
        context['selected_seat'] = selected_seat
        context['reservation_number'] = reservation_number
        

v2/backend/myproject/deicafe_app/templates/reservation/confirm.html
{% extends "base/base.html" %}

{% block title %}予約内容確認{% endblock %}

{% block main_padding %}pt-24{% endblock %}

{% block content %}
{% include 'base/header.html' %}
<div class="flex flex-col mx-auto w-full max-w-xl">

  <div class="flex flex-col items-center mb-10 w-full">
    <p class="h-auto text-2xl mb-10 font-bold">予約内容をご確認ください</p>
    <div class="w-10/12 border bg-gray-100 rounded-md">
      <div class="flex w-full border-b">
        <div class="w-2/5">予約日時：</div>
        <div class="w-3/5 text-center">
          {{ reservation_draft.date }} {{ reservation_draft.time_start }} ~ {{ reservation_draft.time_end }}
        </div>
      </div>

      <div class="flex w-full">
        <div class="w-1/3">座席番号：</div>
        <div class="w-2/3 text-center">
          {{ reservation_draft.seat_number }}
        </div>
      </div>
    </div>
  </div>
    
  <div class="flex flex-col h-auto w-10/12 mx-auto">

    <div class="w-full border bg-gray-100 rounded-md">
      <div class="border-b">事前オーダー：</div>
        {% for cart_item in cart_items %}
        <div class="flex w-full">
          <div class="w-2/4">{{ cart_item.product.name }}</div>
          <div class="w-1/4 text-center">{{ cart_item.quantity }}点</div>
          <div class="w-1/4 text-center">¥{{ cart_item.total }}</div>
        </div>
        {% endfor %}


      <div class="flex w-full border-t bg-gray-200">
        <div class="w-3/4">小計</div>
        <div class="w-1/4 text-center">¥{{ reservation_draft.cart_total }}</div>
      </div>

      <div class="flex w-full border-t">
        <div class="w-3/4">事前オーダー値引き(10%)</div>
        <div class="w-1/4 text-center">-¥{{ reservation_draft.cart_discount_amount }}</div>
      </div>

      <div class="flex w-full border-t bg-gray-200">
        <div class="w-3/4">小計</div>
        <div class="w-1/4 text-center">¥{{ reservation_draft.cart_total_after_discount }}</div>
      </div>

      <div class="flex w-full border-t">
        <div class="w-3/4">消費税(10%)</div>
        <div class="w-1/4 text-center">¥{{ reservation_draft.cart_tax_amount }}</div>
      </div>

      <div class="flex w-full border-t-2 text-xl font-bold bg-gray-200">
        <div class="w-2/4">合計</div>
        <div class="w-1/4 text-center">{{ reservation_draft.item_count }}点</div>
        <div class="w-1/4 text-center">¥{{ reservation_draft.cart_total_with_tax }}</div>
      </div>

    </div>
  </div>
  <form method="post" action="{% url 'user:reservation_done' %}" id="reservationForm">
    {% csrf_token %}
    {% with back_url="user:reservation_main" next_text="予約確定" next_color="bg-green-600" form_id="reservationForm" %}
      {% include 'base/footer.html' %}
    {% endwith %}
  </form>
</div>
{% endblock%}

v2/backend/myproject/deicafe_app/templates/reservation/main.html
{% extends "base/base.html" %}

{% block title %}予約{% endblock %}

{% block main_padding %}pt-24{% endblock %}

{% block content %}
{% include 'base/header.html' %}
<div class="flex flex-col items-center mx-auto w-full max-w-xl">

  <div class="flex flex-col items-center mb-10 w-full">
    <a
      type="submit"
      class="flex items-center justify-center bg-green-600 text-white text-center p-2 rounded-md w-32 mb-5"
      {% if not reservation_draft %}
        href="{% url 'user:reservation_calendar' %}?week_offset=0&seat=1"
      {% endif %}
    >
      <span class="material-symbols-outlined">
        calendar_month
      </span>
      座席予約
    </a>

    <div class="w-full rounded-md">
        {% if reservation_draft %}
          <div class="flex justify-center w-10/12 mx-auto items-center">

            <div class="flex w-full bg-gray-100 border rounded-md mb-2">
              <div class="w-full">
                <div class="flex w-full text-center items-center">
                  <div class="w-1/4">予約日時</div>
                  <div class="w-3/4 border-l border-r">
                    {{ reservation_draft.date }} {{ reservation_draft.time_start }} ~ {{ reservation_draft.time_end }}
                  </div>
                </div>

                <div class="flex w-full text-center items-center">
                  <div class="w-1/4">座席番号</div>
                  <div class="w-3/4 border-l border-r">
                    {{ reservation_draft.seat_number }}
                  </div>
                </div>
              </div>

              <form 
                action="{% url 'user:delete_reservation_draft' reservation_draft.id %}"
                method="post"
                class="flex items-center justify-center"
              >
                {% csrf_token %}
                <button class="flex items-center justify-center p-2">
                  <span class="material-symbols-outlined text-gray-500">
                    remove
                  </span>
                </button>
              </form>
            </div>

          </div>
      {% else %}
        <div class="text-center text-gray-500">
          予約する座席を選択してください
        </div>
      {% endif %}
    </div>
  </div>

  <div class="flex flex-col items-center h-auto w-full">
    <a
      type="submit"
      class="flex items-center justify-center bg-green-600 text-white text-center p-2 rounded-md w-32 mb-5"
      href="{% url 'user:reservation_pre_order' %}"
    >
      <span class="material-symbols-outlined">
        shopping_cart
      </span>
      商品カート
    </a>
    <p class="text-sm text-red-500">事前オーダーで商品価格10%off！</p>

    {% if cart_items %}
      <div class="w-10/12 mx-auto rounded-md">
        {% for cart_item in cart_items %}
          <div class="flex items-center border rounded-md bg-gray-100 mb-2">

            <div class="w-3/5">{{ cart_item.product.name }}</div>
            <div class="flex w-2/5">
              <div class="border-l w-2/5 text-center">{{ cart_item.quantity }}点</div>
              <div class="flex items-center w-3/5">
                <div class="text-sm border-l w-1/2 text-center" style="text-decoration: line-through double; text-decoration-color: #EF4444;" >
                  ¥{{ cart_item.total }}
                </div>
                <div class="w-1/2 text-center">
                  ¥{{ cart_item.total_after_discount }}
                </div>
              </div>
            </div>

            <form method="post" action="{% url 'user:delete_cart_item' cart_item.id %}">
              {% csrf_token %}
              <button class="flex items-center justify-center border-l p-2">
                <span class="material-symbols-outlined text-gray-500">
                  remove
                </span>
              </button>
            </form>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="w-full text-center text-gray-500">カートは空です</div>
    {% endif %}
  </div>
  {% with back_url="user:home" next_text="確認" next_url=reservation_draft|yesno:"user:reservation_confirm,user:reservation_main" %}
    {% include 'base/footer.html' %}
  {% endwith %}
</div>
{% endblock%}

v2/backend/myproject/deicafe_app/templates/reservation/pre-order.html
{% extends "base/base.html" %}

{% block title %}事前オーダー{% endblock %}

{% block main_padding %}pt-24{% endblock %}

{% block content %}
{% include 'base/header.html' %}

<div class="mx-auto w-full max-w-5xl">
  <form method="POST">
    {% csrf_token %}
    {% if products %}
      <div class="flex flex-wrap justify-center items-center">
        {% for product in products %}
        <div class="m-2">
          <div class="flex flex-col justify-between rounded shadow-md w-48 h-48 m-5 p-2">
            <div>
              <p class="text-center p-2">{{ product.name }}</p>
              <p class="text-center">¥{{ product.price }}</p>
            </div>
            <button 
              class="bg-green-600 text-white h-8 rounded"
              type="submit"
              name="product_id"
              value="{{ product.id }}">
              追加
            </button>
          </div>
        </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="text-center">商品がありません</div>
    {% endif %}
  </form>
  {% with back_url="user:reservation_main" %}
    {% include 'base/footer2.html' %}
  {% endwith %}
</div>
{% endblock %}